import {test} from 'node:test';import {strict as assert} from 'node:assert';import {mkdtempSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
process.env.DATA_FILE=join(mkdtempSync(join(tmpdir(),'veya-community-')),'test.sqlite');
const auth=await import('../auth.mjs');const access=await import('../access.mjs');const community=await import('../community.mjs');
const make=name=>{const u=auth.register({email:name+'@example.test',displayName:name,password:'a long test password',adult:true});return auth.saveProfile(u.id,{displayName:name,country:'GB',adult:true,bio:'Hello',avatar:'',interests:[]});};
const owner=make('Owner');process.env.ADMIN_USER_IDS=owner.id;const viewer=make('Viewer'),host=make('Host'),pending=make('Pending');for(const u of [viewer,host])access.manage(owner,{action:'tester',userId:u.id,approved:true});access.manage(owner,{action:'host',userId:host.id,status:'trial',days:10});
test('public profiles keep account data private and follow only visible approved hosts',()=>{auth.saveProfile(host.id,{displayName:host.displayName,country:'GB',adult:true,bio:'Hello',avatar:'',interests:[],age:25,hobbies:['Cooking','Music']});const p=community.publicProfile(viewer,host.id);assert.equal(p.age,25);assert.deepEqual(p.hobbies,['Cooking','Music']);assert.equal(p.country,'GB');assert.deepEqual(Object.keys(p).sort(),['banner','theme','country','age','hobbies','avatar','bio','displayName','followers','following','id','isFollowing','isHost'].sort());assert.throws(()=>community.publicProfile(viewer,pending.id),/unavailable/);assert.throws(()=>community.follow(viewer,viewer.id,true),/yourself/);assert.throws(()=>community.follow(host,viewer.id,true),/approved host/);community.follow(viewer,host.id,true);community.follow(viewer,host.id,true);assert.equal(community.publicProfile(viewer,host.id).followers,1);assert.equal(community.people(viewer,{following:true})[0].id,host.id);});
test('live notifications deduplicate, remain private, and mark only owned records',()=>{const room={id:'room-one',hostId:host.id,hostName:'Host',title:'Hello live'};community.notifyLive(room);community.notifyLive(room);const n=community.notifications(viewer);assert.equal(n.items.length,1);assert.equal(n.unread,1);community.readNotifications(host,[n.items[0].id]);assert.equal(community.notifications(viewer).unread,1);community.readNotifications(viewer,[n.items[0].id]);assert.equal(community.notifications(viewer).unread,0);assert.throws(()=>community.readNotifications(viewer,['wrong']),/Invalid/);});
test('host activity is isolated and revoked hosts disappear from discovery',()=>{access.startHours({id:'session-one'},host);access.touchHours({id:'session-one'});access.endHours({id:'session-one'});assert.equal(community.hostDashboard(host).stats.sessions,1);assert.equal(community.hostDashboard(viewer).stats.sessions,0);access.manage(owner,{action:'host',userId:host.id,status:'viewer'});assert.equal(community.people(viewer,{hostsOnly:true}).some(p=>p.id===host.id),false);community.follow(viewer,host.id,false);assert.equal(community.people(viewer,{following:true}).length,0);access.manage(owner,{action:'block',userId:host.id,kind:'account',reason:'Suspended'});assert.throws(()=>community.publicProfile(viewer,host.id),/unavailable/);});
test('community HTTP APIs require sign-in, tester access and same-origin mutations',async()=>{const {createApp}=await import('../server.mjs');const {server}=createApp();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;const cookie=`veya_session=${auth.createSession(viewer.id)}`;try{assert.equal((await fetch(base+'/api/people')).status,401);assert.equal((await fetch(base+'/api/people',{headers:{Cookie:`veya_session=${auth.createSession(pending.id)}`}})).status,403);const p=await fetch(base+'/api/public-profile?id='+owner.id,{headers:{Cookie:cookie}});assert.equal(p.status,200);assert.equal((await p.json()).profile.email,undefined);assert.equal((await fetch(base+'/api/follow',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json',Origin:'https://wrong.example'},body:JSON.stringify({userId:owner.id,enabled:true})})).status,403);const followed=await fetch(base+'/api/follow',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json',Origin:base},body:JSON.stringify({userId:owner.id,enabled:true})});assert.equal(followed.status,200);assert.equal((await followed.json()).profile.isFollowing,true);}finally{await new Promise(r=>server.close(r));}});
