import {userById,saveProfile,setProfileState} from './auth.mjs';
import {DatabaseSync} from 'node:sqlite';
import {randomBytes} from 'node:crypto';
import {resolve,dirname} from 'node:path';
import {mkdirSync} from 'node:fs';
import {isIP} from 'node:net';
mkdirSync(dirname(resolve(process.env.DATA_FILE || './data/veya.sqlite')),{recursive:true});
const db=new DatabaseSync(resolve(process.env.DATA_FILE || './data/veya.sqlite'));
db.exec(`CREATE TABLE IF NOT EXISTS access_members (user_id TEXT PRIMARY KEY, tester INTEGER NOT NULL DEFAULT 0, host_status TEXT NOT NULL DEFAULT 'viewer', trial_end INTEGER, application TEXT NOT NULL DEFAULT '', last_ip TEXT NOT NULL DEFAULT '', phone TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS admin_permissions (user_id TEXT PRIMARY KEY, permissions TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS access_settings (id INTEGER PRIMARY KEY CHECK(id=1), value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS access_blocks (id TEXT PRIMARY KEY, kind TEXT NOT NULL, value TEXT NOT NULL, reason TEXT NOT NULL, expires_at INTEGER, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS appeals (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, message TEXT NOT NULL, created_at TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', response TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS host_sessions (room_id TEXT PRIMARY KEY, user_id TEXT NOT NULL, started_at INTEGER NOT NULL, last_seen INTEGER NOT NULL, ended_at INTEGER);
CREATE TABLE IF NOT EXISTS access_audit (id TEXT PRIMARY KEY, actor_id TEXT NOT NULL, action TEXT NOT NULL, target TEXT NOT NULL, created_at TEXT NOT NULL);`);
export const PERMISSIONS=['testers','hosts','moderation','settings','appeals','profiles','gifts'];
export const ownerIds=()=>String(process.env.ADMIN_USER_IDS || '').split(',').map(x=>x.trim()).filter(Boolean);
export const isOwner=user=>Boolean(user && ownerIds().includes(user.id));
export function permissionsFor(user){if(!user)return [];if(isOwner(user))return PERMISSIONS;if(db.prepare("SELECT id FROM access_blocks WHERE kind='account' AND value=? AND active=1 AND (expires_at IS NULL OR expires_at>?)").get(user.id,Date.now()))return [];const row=db.prepare('SELECT permissions FROM admin_permissions WHERE user_id=?').get(user.id);return row?JSON.parse(row.permissions):[];}
export const hasPermission=(user,permission)=>permissionsFor(user).includes(permission);
export const settings=()=>({...{testingApproval:true,trialDays:15,trialOutcome:'review',paidTrial:false,trialAmount:0,minimumHours:0,minimumDays:0,dailyHourCap:0},...JSON.parse(db.prepare('SELECT value FROM access_settings WHERE id=1').get()?.value || '{}')});
const member=id=>{db.prepare('INSERT OR IGNORE INTO access_members(user_id) VALUES(?)').run(id);return db.prepare('SELECT * FROM access_members WHERE user_id=?').get(id);};
if(!db.prepare('PRAGMA table_info(access_blocks)').all().some(c=>c.name==='group_id'))db.exec("ALTER TABLE access_blocks ADD COLUMN group_id TEXT NOT NULL DEFAULT ''");
export function clientIP(req){const value=process.env.RAILWAY_ENVIRONMENT_ID?req?.headers?.['x-real-ip']:req?.socket?.remoteAddress;return typeof value==='string' && isIP(value)?value.replace(/^::ffff:/,''):'';}
export function rememberConnection(user,req){if(user){member(user.id);db.prepare('UPDATE access_members SET last_ip=? WHERE user_id=?').run(clientIP(req),user.id);}}
export function blocked(user,req){if(!user || isOwner(user))return null;const m=member(user.id),ip=clientIP(req);return db.prepare("SELECT reason FROM access_blocks WHERE active=1 AND (expires_at IS NULL OR expires_at>?) AND ((kind='account' AND value=?) OR (kind='ip' AND value=?) OR (kind='phone' AND value=?)) ORDER BY rowid DESC LIMIT 1").get(Date.now(),user.id,ip,m.phone || '__none__') || null;}
export function accessFor(user,req){if(!user)return {};const m=member(user.id),s=settings(),block=blocked(user,req),owner=isOwner(user);const trialExpired=m.host_status==='trial' && m.trial_end<=Date.now();return {owner,permissions:permissionsFor(user),tester:owner || Boolean(m.tester),accessAllowed:!block && (!s.testingApproval || owner || Boolean(m.tester)),blocked:Boolean(block),blockReason:block?.reason || '',hostStatus:trialExpired ? 'review' : m.host_status,canHost:!block && !userById(user.id)?.profileRemoved && (owner || m.host_status==='approved' || (m.host_status==='trial' && !trialExpired)),trialEnd:m.trial_end,applicationPending:m.host_status==='pending',phone:m.phone,liveHours:Math.round((db.prepare('SELECT COALESCE(SUM(last_seen-started_at),0) AS ms FROM host_sessions WHERE user_id=?').get(user.id).ms / 3600000)*100)/100};}
export function assertAccess(user,req,hosting=false){const a=accessFor(user,req);if(a.blocked)throw Error('Your account access is suspended. You can submit an appeal from My profile.');if(!a.accessAllowed)throw Error('Your tester access is waiting for admin approval.');if(hosting && !a.canHost)throw Error('Streaming requires host approval. Apply from My profile.');}
const audit=(user,action,target)=>db.prepare('INSERT INTO access_audit VALUES(?,?,?,?,?)').run(randomBytes(16).toString('hex'),user.id,action,target,new Date().toISOString());
export function applyHost(user,input){const m=member(user.id);if(!user.onboarded || !user.country)throw Error('Complete your profile and country first');if(['pending','trial','approved'].includes(m.host_status))throw Error('Your application or host access is already active');const value={};for(const field of ['bio','languages','experience','socialLinks','contact'])value[field]=String(input[field] || '').trim().slice(0,500);db.prepare("UPDATE access_members SET host_status='pending',application=? WHERE user_id=?").run(JSON.stringify({...value,submittedAt:new Date().toISOString()}),user.id);}
export function savePhone(user,value){value=String(value || '').replace(/[\s()-]/g,'');if(value && !/^\+[1-9][0-9]{6,14}$/.test(value))throw Error('Use international format, for example +447…');member(user.id);db.prepare('UPDATE access_members SET phone=? WHERE user_id=?').run(value,user.id);}
export function appeal(user,message){message=String(message || '').trim();if(message.length<10 || message.length>1000)throw Error('Use 10 to 1000 characters for your appeal');if(db.prepare("SELECT id FROM appeals WHERE user_id=? AND status='open'").get(user.id))throw Error('You already have an open appeal');db.prepare('INSERT INTO appeals(id,user_id,message,created_at) VALUES(?,?,?,?)').run(randomBytes(16).toString('hex'),user.id,message,new Date().toISOString());}
export const ownAppeals=user=>db.prepare('SELECT id,message,created_at,status,response FROM appeals WHERE user_id=? ORDER BY created_at DESC LIMIT 20').all(user.id);
export function management(user){if(!permissionsFor(user).length)throw Error('Admin access required');const p=permissionsFor(user);return {owner:isOwner(user),permissions:p,settings:p.includes('settings')?settings():null,members:p.some(x=>['testers','hosts','moderation','profiles'].includes(x))?db.prepare('SELECT u.id,u.display_name AS name,u.email,p.country,p.profile_locked,p.profile_removed,a.tester,a.host_status,a.trial_end,a.application,a.last_ip,a.phone FROM users u LEFT JOIN profiles p ON p.user_id=u.id LEFT JOIN access_members a ON a.user_id=u.id ORDER BY u.created_at DESC LIMIT 200').all().map(m=>({...m,permissions:isOwner(user)?permissionsFor({id:m.id}):undefined})):[],blocks:p.includes('moderation')?db.prepare('SELECT * FROM access_blocks WHERE active=1 ORDER BY rowid DESC LIMIT 200').all():[],appeals:p.includes('appeals')?db.prepare('SELECT a.*,u.display_name AS name FROM appeals a JOIN users u ON u.id=a.user_id ORDER BY created_at DESC LIMIT 200').all():[],audit:isOwner(user)?db.prepare('SELECT * FROM access_audit ORDER BY created_at DESC LIMIT 100').all():[]};}
export function manage(user,input){
 const action=input.action,id=String(input.userId || '');
 const requirePermission=p=>{if(!hasPermission(user,p))throw Error('You do not have permission for this action');};
 const target=()=>{if(!db.prepare('SELECT id FROM users WHERE id=?').get(id))throw Error('Account not found');if(isOwner({id}))throw Error('Owner access cannot be changed here');member(id);};
 if(action==='tester'){requirePermission('testers');target();db.prepare('UPDATE access_members SET tester=? WHERE user_id=?').run(input.approved===true?1:0,id);}
 else if(action==='host'){requirePermission('hosts');target();if(!['trial','approved','viewer','rejected'].includes(input.status))throw Error('Choose a host status');const current=member(id);if(input.status==='approved' && !['trial','approved'].includes(current.host_status))throw Error('New hosts must start on a trial');const days=Number(input.days ?? settings().trialDays);if(input.status==='trial' && (!Number.isInteger(days)||days<1||days>365))throw Error('Trial must be 1 to 365 days');if(['trial','approved'].includes(input.status)){const p=db.prepare('SELECT country,completed FROM profiles WHERE user_id=?').get(id);if(!p?.country || !p.completed)throw Error('The applicant must complete their profile first');}db.prepare('UPDATE access_members SET host_status=?,trial_end=? WHERE user_id=?').run(input.status,input.status==='trial'?Date.now()+days*86400000:null,id);}
 else if(action==='settings'){requirePermission('settings');const s=settings();for(const field of ['trialDays','minimumHours','minimumDays','dailyHourCap','trialAmount']){const n=Number(input[field]);if(!Number.isFinite(n)||n<0||n>({trialDays:365,minimumHours:168,minimumDays:7,dailyHourCap:24,trialAmount:10000}[field])||(field==='trialDays'&&(n<1||!Number.isInteger(n))))throw Error('Check the trial settings');s[field]=n;}if(!['review','continue'].includes(input.trialOutcome))throw Error('Choose a trial outcome');s.trialOutcome=input.trialOutcome;s.paidTrial=input.paidTrial===true;s.testingApproval=input.testingApproval!==false;db.prepare('INSERT INTO access_settings VALUES(1,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value').run(JSON.stringify(s));}
 else if(action==='permissions'){if(!isOwner(user))throw Error('Only the owner can change admin permissions');target();if(!Array.isArray(input.permissions)||input.permissions.some(p=>!PERMISSIONS.includes(p)))throw Error('Invalid permissions');db.prepare('INSERT INTO admin_permissions VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET permissions=excluded.permissions').run(id,JSON.stringify([...new Set(input.permissions)]));}
 else if(action==='block'){requirePermission('moderation');target();const m=member(id),kind=input.kind;if(!['account','ip','phone'].includes(kind))throw Error('Choose a suspension type');const value=kind==='account'?id:kind==='ip'?m.last_ip:m.phone;if(!value)throw Error('This account has no saved value for that suspension type');if(kind!=='account' && db.prepare('SELECT user_id,last_ip,phone FROM access_members').all().some(x=>isOwner({id:x.user_id}) && (kind==='ip'?x.last_ip:x.phone)===value))throw Error('That value is also used by the owner');const reason=String(input.reason || '').trim().slice(0,500);if(!reason)throw Error('Enter a reason');const days=Number(input.days || 0);if(!Number.isFinite(days)||days<0||days>365)throw Error('Use 0 for permanent, or up to 365 days');const group=randomBytes(16).toString('hex'),expires=days?Date.now()+days*86400000:null;for(const [blockKind,blockValue] of kind==='account' ? [[kind,value]] : [[kind,value],['account',id]])db.prepare('INSERT INTO access_blocks(id,kind,value,reason,expires_at,group_id) VALUES(?,?,?,?,?,?)').run(randomBytes(16).toString('hex'),blockKind,blockValue,reason,expires,group);}
 else if(action==='unblock'){requirePermission('moderation');const b=db.prepare('SELECT group_id FROM access_blocks WHERE id=?').get(String(input.blockId));if(b?.group_id)db.prepare('UPDATE access_blocks SET active=0 WHERE group_id=?').run(b.group_id);else db.prepare('UPDATE access_blocks SET active=0 WHERE id=?').run(String(input.blockId));}
 else if(action==='appeal'){requirePermission('appeals');if(!['reviewed','open'].includes(input.status))throw Error('Choose appeal status');db.prepare('UPDATE appeals SET status=?,response=? WHERE id=?').run(input.status,String(input.response || '').trim().slice(0,1000),String(input.appealId));}
 else throw Error('Unknown admin action');
 audit(user,action,id || String(input.blockId || input.appealId || 'settings'));
}
export function expireTrials(){if(settings().trialOutcome==='continue')db.prepare("UPDATE access_members SET host_status='approved',trial_end=NULL WHERE host_status='trial' AND trial_end<=?").run(Date.now());}
export function startHours(room,user){const now=Date.now();db.prepare('INSERT OR IGNORE INTO host_sessions VALUES(?,?,?,?,NULL)').run(room.id,user.id,now,now);}
export function touchHours(room){db.prepare('UPDATE host_sessions SET last_seen=? WHERE room_id=? AND ended_at IS NULL').run(Date.now(),room.id);}
export function endHours(room){db.prepare('UPDATE host_sessions SET last_seen=?,ended_at=? WHERE room_id=? AND ended_at IS NULL').run(Date.now(),Date.now(),room.id);}

export function adminProfile(user,id,input){
 if(!hasPermission(user,'profiles'))throw Error('Profile management permission required');
 const target=userById(id);if(!target)throw Error('Account not found');
 if(input===undefined)return target;
 if(isOwner({id}) && !isOwner(user))throw Error('Owner profile is protected');
 if(isOwner({id}) && ['lock','remove'].includes(input.action))throw Error('Owner profile cannot be locked or removed');
 const result=input.action==='save'?saveProfile(id,input.profile,{admin:true}):setProfileState(id,input.action);
 audit(user,'profile-'+input.action,id);return result;
}
