import {storedHobbies} from './hobbies.mjs';
import {DatabaseSync} from 'node:sqlite';
import {resolve,dirname} from 'node:path';
import {mkdirSync} from 'node:fs';
import {randomBytes} from 'node:crypto';
import {isOwner,accessFor,settings} from './access.mjs';
const file=resolve(process.env.DATA_FILE || './data/veya.sqlite');mkdirSync(dirname(file),{recursive:true});
const db=new DatabaseSync(file);
db.exec(`CREATE TABLE IF NOT EXISTS follows (follower_id TEXT NOT NULL, target_id TEXT NOT NULL, created_at INTEGER NOT NULL, PRIMARY KEY(follower_id,target_id));
CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,kind TEXT NOT NULL,message TEXT NOT NULL,actor_id TEXT,room_id TEXT,created_at INTEGER NOT NULL,seen INTEGER NOT NULL DEFAULT 0,dedupe TEXT NOT NULL,UNIQUE(user_id,dedupe));`);
function visible(id){const row=db.prepare('SELECT u.id,u.adult_ack,u.display_name AS name,p.bio,p.avatar,p.banner,p.theme,p.profile_removed,p.age,p.hobbies,p.completed,p.country,a.tester,a.host_status FROM users u JOIN profiles p ON p.user_id=u.id LEFT JOIN access_members a ON a.user_id=u.id WHERE u.id=?').get(id);if(row?.profile_removed || !row?.adult_ack || !row?.completed || !row.country || (!isOwner({id}) && settings().testingApproval && !row.tester) || accessFor({id}).blocked)return null;return row;}
export function publicProfile(viewer,id){const row=visible(String(id));if(!row)throw Error('Profile is unavailable');return {id:row.id,displayName:row.name,bio:row.bio,avatar:row.avatar,banner:row.banner,theme:row.theme,age:row.age,hobbies:storedHobbies(row.hobbies),country:row.country,isHost:accessFor({id:row.id}).canHost,followers:db.prepare('SELECT COUNT(*) AS n FROM follows WHERE target_id=?').get(row.id).n,following:db.prepare('SELECT COUNT(*) AS n FROM follows WHERE follower_id=?').get(row.id).n,isFollowing:Boolean(db.prepare('SELECT 1 FROM follows WHERE follower_id=? AND target_id=?').get(viewer.id,row.id))};}
export function people(viewer,{following=false,search='',hostsOnly=false}={}){const pattern='%'+String(search).trim().slice(0,70).replace(/[%_\\]/g,'\\$&')+'%';const ids=following?db.prepare('SELECT target_id AS id FROM follows WHERE follower_id=? ORDER BY created_at DESC LIMIT 200').all(viewer.id):db.prepare("SELECT u.id FROM users u LEFT JOIN profiles p ON p.user_id=u.id WHERE u.display_name LIKE ? ESCAPE '\\' OR p.bio LIKE ? ESCAPE '\\' OR p.hobbies LIKE ? ESCAPE '\\' ORDER BY u.created_at DESC LIMIT 200").all(pattern,pattern,pattern);return ids.map(({id})=>{try{const p=publicProfile(viewer,id);delete p.banner;return p;}catch{return null;}}).filter(p=>p && (!hostsOnly || p.isHost));}
export function connections(viewer,id,kind,offset=0){
 const target=publicProfile(viewer,id);
 if(!['followers','following'].includes(kind))throw Error('Choose followers or following');
 if(!Number.isSafeInteger(offset)||offset<0||offset>1000000)throw Error('Invalid list position');
 const rows=kind==='followers'?db.prepare('SELECT follower_id AS id FROM follows WHERE target_id=? ORDER BY created_at DESC,follower_id DESC LIMIT 51 OFFSET ?').all(target.id,offset):db.prepare('SELECT target_id AS id FROM follows WHERE follower_id=? ORDER BY created_at DESC,target_id DESC LIMIT 51 OFFSET ?').all(target.id,offset);
 return {profile:{id:target.id,displayName:target.displayName},kind,nextOffset:rows.length>50?offset+50:null,people:rows.slice(0,50).map(({id})=>{try{const person=publicProfile(viewer,id);delete person.banner;return person;}catch{return null;}}).filter(Boolean)};
}
export function follow(viewer,targetId,enabled){if(targetId===viewer.id)throw Error('You cannot follow yourself');publicProfile(viewer,viewer.id);publicProfile(viewer,targetId);if(enabled){if(!db.prepare('SELECT 1 FROM follows WHERE follower_id=? AND target_id=?').get(viewer.id,targetId)&&db.prepare('SELECT COUNT(*) AS n FROM follows WHERE follower_id=?').get(viewer.id).n>=5000)throw Error('Following limit reached');const inserted=db.prepare('INSERT OR IGNORE INTO follows VALUES(?,?,?)').run(viewer.id,targetId,Date.now());if(inserted.changes)notify(targetId,'follow',`${viewer.displayName} followed you.`,{actorId:viewer.id});}else db.prepare('DELETE FROM follows WHERE follower_id=? AND target_id=?').run(viewer.id,targetId);return publicProfile(viewer,targetId);}
export function notify(userId,kind,message,{actorId=null,roomId=null,dedupe=randomBytes(16).toString('hex')}={}){db.prepare('INSERT OR IGNORE INTO notifications VALUES(?,?,?,?,?,?,?,0,?)').run(randomBytes(16).toString('hex'),userId,kind,message,actorId,roomId,Date.now(),dedupe);db.prepare('DELETE FROM notifications WHERE user_id=? AND id NOT IN (SELECT id FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 500)').run(userId,userId);}
export function notifyLive(room){for(const {follower_id:id} of db.prepare('SELECT follower_id FROM follows WHERE target_id=?').all(room.hostId)){if(!accessFor({id}).blocked)notify(id,'live',`${room.hostName} is live: ${room.title}`,{actorId:room.hostId,roomId:room.id,dedupe:'live:'+room.id});}}
export function notifications(user){return {items:db.prepare('SELECT id,kind,message,actor_id AS actorId,room_id AS roomId,created_at AS createdAt,seen FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 200').all(user.id),unread:db.prepare('SELECT COUNT(*) AS n FROM notifications WHERE user_id=? AND seen=0').get(user.id).n};}
export function readNotifications(user,ids){if(!Array.isArray(ids)||ids.length>200||ids.some(id=>typeof id!=='string'||!/^[0-9a-f]{32}$/.test(id)))throw Error('Invalid notifications');const stmt=db.prepare('UPDATE notifications SET seen=1 WHERE user_id=? AND id=?');for(const id of ids)stmt.run(user.id,id);}
export function hostDashboard(user,req){const access=accessFor(user,req);const s=settings();const rows=db.prepare('SELECT room_id AS roomId,started_at AS startedAt,last_seen AS lastSeen,ended_at AS endedAt FROM host_sessions WHERE user_id=? ORDER BY started_at DESC LIMIT 30').all(user.id);const stats=db.prepare('SELECT COUNT(*) AS sessions,COALESCE(SUM(last_seen-started_at),0) AS ms,COUNT(DISTINCT date(started_at/1000,\'unixepoch\')) AS days FROM host_sessions WHERE user_id=?').get(user.id);return {access,stats:{sessions:stats.sessions,hours:Math.round(stats.ms/36000)/100,days:stats.days},sessions:rows,trial:{endsAt:access.trialEnd,status:access.hostStatus,expired:access.hostStatus==='review',requirements:{hours:s.minimumHours,days:s.minimumDays,dailyCap:s.dailyHourCap},paidPlanning:s.paidTrial},application:db.prepare('SELECT application FROM access_members WHERE user_id=?').get(user.id)?.application || ''};}
