import {storedHobbies} from './hobbies.mjs';
import {userById} from './auth.mjs';
import {DatabaseSync} from 'node:sqlite';
import {resolve,dirname} from 'node:path';
import {mkdirSync} from 'node:fs';
import {randomBytes} from 'node:crypto';
import {isOwner,accessFor,settings,hasPermission} from './access.mjs';
const file=resolve(process.env.DATA_FILE || './data/veya.sqlite');mkdirSync(dirname(file),{recursive:true});
const db=new DatabaseSync(file);
db.exec(`CREATE TABLE IF NOT EXISTS follows (follower_id TEXT NOT NULL, target_id TEXT NOT NULL, created_at INTEGER NOT NULL, PRIMARY KEY(follower_id,target_id));
CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,kind TEXT NOT NULL,message TEXT NOT NULL,actor_id TEXT,room_id TEXT,created_at INTEGER NOT NULL,seen INTEGER NOT NULL DEFAULT 0,dedupe TEXT NOT NULL,UNIQUE(user_id,dedupe));`);
db.exec(`CREATE TABLE IF NOT EXISTS moments (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,caption TEXT NOT NULL,image TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS moments_user_date ON moments(user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS moment_likes (moment_id TEXT NOT NULL,user_id TEXT NOT NULL,PRIMARY KEY(moment_id,user_id));
CREATE TABLE IF NOT EXISTS moment_comments (id TEXT PRIMARY KEY,moment_id TEXT NOT NULL,user_id TEXT NOT NULL,body TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS moment_comments_moment_date ON moment_comments(moment_id,created_at DESC);`);
function visible(id){const row=db.prepare('SELECT u.id,u.adult_ack,u.display_name AS name,p.bio,p.avatar,p.banner,p.theme,p.profile_removed,p.age,p.hobbies,p.completed,p.country,a.tester,a.host_status FROM users u JOIN profiles p ON p.user_id=u.id LEFT JOIN access_members a ON a.user_id=u.id WHERE u.id=?').get(id);if(row?.profile_removed || !row?.adult_ack || !row?.completed || !row.country || (!isOwner({id}) && settings().testingApproval && !row.tester) || accessFor({id}).blocked)return null;return row;}
export function publicProfile(viewer,id){const row=visible(String(id));if(!row)throw Error('Profile is unavailable');return {id:row.id,displayName:row.name,bio:row.bio,avatar:row.avatar,banner:row.banner,theme:row.theme,age:row.age,hobbies:storedHobbies(row.hobbies),country:row.country,isHost:accessFor({id:row.id}).canHost,followers:db.prepare('SELECT COUNT(*) AS n FROM follows WHERE target_id=?').get(row.id).n,following:db.prepare('SELECT COUNT(*) AS n FROM follows WHERE follower_id=?').get(row.id).n,isFollowing:Boolean(db.prepare('SELECT 1 FROM follows WHERE follower_id=? AND target_id=?').get(viewer.id,row.id))};}
export function people(viewer,{following=false,search='',hostsOnly=false}={}){const pattern='%'+String(search).trim().slice(0,70).replace(/[%_\\]/g,'\\$&')+'%';const ids=following?db.prepare('SELECT target_id AS id FROM follows WHERE follower_id=? ORDER BY created_at DESC LIMIT 200').all(viewer.id):db.prepare("SELECT u.id FROM users u LEFT JOIN profiles p ON p.user_id=u.id WHERE u.display_name LIKE ? ESCAPE '\\' OR p.bio LIKE ? ESCAPE '\\' OR p.hobbies LIKE ? ESCAPE '\\' ORDER BY u.created_at DESC LIMIT 200").all(pattern,pattern,pattern);return ids.map(({id})=>{try{const p=publicProfile(viewer,id);delete p.banner;return p;}catch{return null;}}).filter(p=>p && (!hostsOnly || p.isHost));}
export function connections(viewer,id,kind,offset=0){
 const target=publicProfile(viewer,id);
 if(!['followers','following'].includes(kind))throw Error('Choose followers or following');
 if(!Number.isSafeInteger(offset)||offset<0||offset>1000000)throw Error('Invalid list position');
 const rows=kind==='followers'?db.prepare('SELECT follower_id AS id FROM follows WHERE target_id=? ORDER BY created_at DESC,follower_id DESC LIMIT 51 OFFSET ?').all(target.id,offset):db.prepare('SELECT target_id AS id FROM follows WHERE follower_id=? ORDER BY created_at DESC,target_id DESC LIMIT 51 OFFSET ?').all(target.id,offset);
 return {profile:{id:target.id,displayName:target.displayName},kind,nextOffset:rows.length>50?offset+50:null,people:rows.slice(0,50).map(({id})=>{try{const person=publicProfile(viewer,id);delete person.banner;return person;}catch{return null;}}).filter(Boolean)};
}
export function follow(viewer,targetId,enabled){if(targetId===viewer.id)throw Error('You cannot follow yourself');publicProfile(viewer,viewer.id);publicProfile(viewer,targetId);if(enabled){if(!db.prepare('SELECT 1 FROM follows WHERE follower_id=? AND target_id=?').get(viewer.id,targetId)&&db.prepare('SELECT COUNT(*) AS n FROM follows WHERE follower_id=?').get(viewer.id).n>=5000)throw Error('Following limit reached');const inserted=db.prepare('INSERT OR IGNORE INTO follows VALUES(?,?,?)').run(viewer.id,targetId,Date.now());if(inserted.changes)notify(targetId,'follow',`${viewer.displayName} followed you.`,{actorId:viewer.id});}else db.prepare('DELETE FROM follows WHERE follower_id=? AND target_id=?').run(viewer.id,targetId);return publicProfile(viewer,targetId);}
export function moments(viewer,id){publicProfile(viewer,id);return db.prepare(`SELECT m.id,m.caption,m.image,m.created_at AS createdAt,(SELECT COUNT(*) FROM moment_likes l WHERE l.moment_id=m.id) AS likes,(SELECT COUNT(*) FROM moment_comments c WHERE c.moment_id=m.id) AS comments,EXISTS(SELECT 1 FROM moment_likes l WHERE l.moment_id=m.id AND l.user_id=?) AS liked FROM moments m WHERE m.user_id=? ORDER BY m.created_at DESC,m.id DESC LIMIT 20`).all(viewer.id,id).map(m=>({...m,liked:Boolean(m.liked)}));}
function readableMoment(viewer,id){publicProfile(viewer,viewer.id);const row=db.prepare('SELECT user_id FROM moments WHERE id=?').get(id);if(!row)throw Error('Moment unavailable');publicProfile(viewer,row.user_id);return row;}
export function momentComments(viewer,id){readableMoment(viewer,id);return db.prepare('SELECT id,user_id AS userId,body,created_at AS createdAt FROM moment_comments WHERE moment_id=? ORDER BY created_at ASC,id ASC LIMIT 100').all(id).map(c=>{try{const p=publicProfile(viewer,c.userId);return {...c,name:p.displayName};}catch{return null;}}).filter(Boolean);}
export function momentReportTarget(viewer,id){const row=readableMoment(viewer,id);if(row.user_id===viewer.id)throw Error('You cannot report your own Moment');const m=db.prepare('SELECT caption FROM moments WHERE id=?').get(id);const profile=publicProfile(viewer,row.user_id);return {id,ownerId:row.user_id,ownerName:profile.displayName,excerpt:m.caption.slice(0,160)};}
export function addMomentComment(user,id,body){const moment=readableMoment(user,id);if(typeof body!=='string'||!body.trim()||body.trim().length>300)throw Error('Write a reply under 300 characters');const now=Date.now();if(db.prepare('SELECT 1 FROM moment_comments WHERE user_id=? AND created_at>?').get(user.id,now-3000))throw Error('Wait a moment before replying again');if(db.prepare('SELECT COUNT(*) AS n FROM moment_comments WHERE user_id=? AND created_at>?').get(user.id,now-3600000).n>=30)throw Error('Reply limit reached. Try again later.');if(db.prepare('SELECT COUNT(*) AS n FROM moment_comments WHERE moment_id=?').get(id).n>=100)throw Error('This Moment has reached its reply limit');const commentId=randomBytes(16).toString('hex');db.prepare('INSERT INTO moment_comments VALUES(?,?,?,?,?)').run(commentId,id,user.id,body.trim(),now);if(moment.user_id!==user.id)notify(moment.user_id,'reply',`${user.displayName} replied to your Moment.`,{actorId:user.id});return {id:commentId,userId:user.id,name:user.displayName,body:body.trim(),createdAt:now};}
export function removeMomentComment(user,id){const comment=db.prepare('SELECT c.user_id AS userId,m.user_id AS ownerId FROM moment_comments c JOIN moments m ON m.id=c.moment_id WHERE c.id=?').get(id);if(!comment)throw Error('Reply unavailable');if(comment.userId!==user.id && comment.ownerId!==user.id && !hasPermission(user,'profiles'))throw Error('You cannot remove this reply');if((isOwner({id:comment.userId})||isOwner({id:comment.ownerId}))&&!isOwner(user) && comment.userId!==user.id)throw Error('Owner content is protected');db.prepare('DELETE FROM moment_comments WHERE id=?').run(id);if(comment.userId!==user.id && comment.ownerId!==user.id)db.prepare('INSERT INTO access_audit VALUES(?,?,?,?,?)').run(randomBytes(16).toString('hex'),user.id,'moment-reply-remove',id,new Date().toISOString());}
export function createMoment(user,{caption,image}){
 publicProfile(user,user.id);
 if(userById(user.id)?.profileLocked)throw Error('Profile editing is locked. Contact support to request a change.');
 if(typeof caption!=='string' || caption.trim().length>280 || typeof image!=='string' || image.length>150000 || (!caption.trim()&&!image))throw Error('Add a short caption or a photo under 110 KB');
 if(image){const match=image.match(/^data:image\/jpeg;base64,([A-Za-z0-9+/]+={0,2})$/);if(!match || !Buffer.from(match[1],'base64').subarray(0,3).equals(Buffer.from([255,216,255])))throw Error('Use a JPG photo');}
 if(db.prepare('SELECT COUNT(*) AS n FROM moments WHERE user_id=?').get(user.id).n>=20)throw Error('You can keep up to 20 Moments. Remove one to add another.');
 const id=randomBytes(16).toString('hex');db.prepare('INSERT INTO moments VALUES(?,?,?,?,?)').run(id,user.id,caption.trim(),image,Date.now());return id;
}
export function likeMoment(user,id,enabled){readableMoment(user,id);if(enabled)db.prepare('INSERT OR IGNORE INTO moment_likes VALUES(?,?)').run(id,user.id);else db.prepare('DELETE FROM moment_likes WHERE moment_id=? AND user_id=?').run(id,user.id);return {likes:db.prepare('SELECT COUNT(*) AS n FROM moment_likes WHERE moment_id=?').get(id).n,liked:enabled};}
export function removeMoment(user,id){const row=db.prepare('SELECT user_id FROM moments WHERE id=?').get(id);if(!row)throw Error('Moment unavailable');if(row.user_id!==user.id && !hasPermission(user,'profiles') && !hasPermission(user,'moderation'))throw Error('Profile management permission required');if(row.user_id!==user.id && isOwner({id:row.user_id}) && !isOwner(user))throw Error('Owner profile is protected');db.prepare('DELETE FROM moment_likes WHERE moment_id=?').run(id);db.prepare('DELETE FROM moment_comments WHERE moment_id=?').run(id);db.prepare('DELETE FROM moments WHERE id=?').run(id);if(row.user_id!==user.id)db.prepare('INSERT INTO access_audit VALUES(?,?,?,?,?)').run(randomBytes(16).toString('hex'),user.id,'moment-remove',row.user_id+':'+id,new Date().toISOString());}
export function notify(userId,kind,message,{actorId=null,roomId=null,dedupe=randomBytes(16).toString('hex')}={}){db.prepare('INSERT OR IGNORE INTO notifications VALUES(?,?,?,?,?,?,?,0,?)').run(randomBytes(16).toString('hex'),userId,kind,message,actorId,roomId,Date.now(),dedupe);db.prepare('DELETE FROM notifications WHERE user_id=? AND id NOT IN (SELECT id FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 500)').run(userId,userId);}
export function notifyLive(room){for(const {follower_id:id} of db.prepare('SELECT follower_id FROM follows WHERE target_id=?').all(room.hostId)){if(!accessFor({id}).blocked)notify(id,'live',`${room.hostName} is live: ${room.title}`,{actorId:room.hostId,roomId:room.id,dedupe:'live:'+room.id});}}
export function notifications(user){return {items:db.prepare('SELECT id,kind,message,actor_id AS actorId,room_id AS roomId,created_at AS createdAt,seen FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 200').all(user.id),unread:db.prepare('SELECT COUNT(*) AS n FROM notifications WHERE user_id=? AND seen=0').get(user.id).n};}
export function readNotifications(user,ids){if(!Array.isArray(ids)||ids.length>200||ids.some(id=>typeof id!=='string'||!/^[0-9a-f]{32}$/.test(id)))throw Error('Invalid notifications');const stmt=db.prepare('UPDATE notifications SET seen=1 WHERE user_id=? AND id=?');for(const id of ids)stmt.run(user.id,id);}
export function weeklyActivity(sessions,now,capHours=0){
 const day=86400000;
 const todayStart=Math.floor(now/day)*day,weekday=new Date(todayStart).getUTCDay(),weekStart=todayStart-((weekday+6)%7)*day;
 const daily=new Map();
 for(const session of sessions){
   let cursor=Math.max(session.startedAt,weekStart),end=Math.min(session.lastSeen,now);
   while(cursor<end){const bucket=Math.floor(cursor/day)*day,next=Math.min(end,bucket+day);daily.set(bucket,(daily.get(bucket)||0)+(next-cursor));cursor=next;}
 }
 const todayMs=daily.get(todayStart)||0,weekMs=[...daily.values()].reduce((sum,ms)=>sum+ms,0);
 const capMs=capHours>0?capHours*3600000:Infinity,qualifiedMs=[...daily.values()].reduce((sum,ms)=>sum+Math.min(ms,capMs),0);
 const hours=ms=>Math.round(ms/36000)/100;
 return {todayHours:hours(todayMs),weekHours:hours(weekMs),qualifyingHours:hours(qualifiedMs),weekDays:[...daily.values()].filter(ms=>ms>0).length,weekStart,weekEnd:weekStart+7*day};
}
export function hostDashboard(user,req){
 const access=accessFor(user,req),s=settings(),now=Date.now(),day=86400000,weekStart=Math.floor(now/day)*day-((new Date(now).getUTCDay()+6)%7)*day;
 const rows=db.prepare('SELECT room_id AS roomId,started_at AS startedAt,last_seen AS lastSeen,ended_at AS endedAt FROM host_sessions WHERE user_id=? ORDER BY started_at DESC LIMIT 30').all(user.id);
 const stats=db.prepare('SELECT COUNT(*) AS sessions,COALESCE(SUM(MAX(last_seen-started_at,0)),0) AS ms,COUNT(DISTINCT date(started_at/1000,\'unixepoch\')) AS days FROM host_sessions WHERE user_id=?').get(user.id);
 const sessions=db.prepare('SELECT started_at AS startedAt,last_seen AS lastSeen FROM host_sessions WHERE user_id=? AND last_seen>? AND started_at<?').all(user.id,weekStart,now);
 return {access,stats:{sessions:stats.sessions,hours:Math.round(stats.ms/36000)/100,days:stats.days},activity:weeklyActivity(sessions,now,s.dailyHourCap),sessions:rows,trial:{endsAt:access.trialEnd,status:access.hostStatus,expired:access.hostStatus==='review',requirements:{hours:s.minimumHours,days:s.minimumDays,dailyCap:s.dailyHourCap}},earnings:{status:'not_enabled',message:'Real earnings and payouts are not active. Test gifts have no cash value.'},application:db.prepare('SELECT application FROM access_members WHERE user_id=?').get(user.id)?.application || ''};
}
