// Requires a configured, reachable LiveKit server and Playwright Chromium.
// Uses only synthetic camera/audio devices; it does not record or screenshot streams.
import { chromium } from 'playwright';
import { strict as assert } from 'node:assert';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const directory = mkdtempSync(join(tmpdir(), 'veya-browser-'));
process.env.DATA_FILE = join(directory, 'test.sqlite');
const { createApp } = await import('../server.mjs');
const { createMedia } = await import('../media.mjs');
assert.ok(createMedia().configured, 'Configure a test LiveKit server first');
process.env.ADMIN_USER_IDS='local-test-owner';const {manage}=await import('../access.mjs');
const { server } = createApp(); await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const base = `http://127.0.0.1:${server.address().port}`;
for(const gift of ['heart','star','flower','crown']){const asset=await fetch(`${base}/gifts/${gift}.svg`);assert.equal(asset.status,200);assert.match(asset.headers.get('content-type'),/image\/svg\+xml/);assert.match(await asset.text(),/<svg /);}
const browser = await chromium.launch({ headless: true, args: ['--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream', '--autoplay-policy=no-user-gesture-required'] });
const errors = [];
async function account(name, mobile = false) {
  const context = await browser.newContext({ permissions: ['camera', 'microphone'], viewport: mobile ? { width: 390, height: 844 } : { width: 1280, height: 900 } });
  if(name==='Host')await context.addInitScript(()=>{delete CanvasRenderingContext2D.prototype.filter;});const page = await context.newPage(); page.on('pageerror', error => errors.push(error.message));
  await page.goto(base); await page.locator('#toggleAccount').click();
  await page.locator('#displayName').fill(name); await page.locator('#adult').check(); await page.locator('#email').fill(`${name}@example.test`); await page.locator('#password').fill('a very long test password'); await page.locator('#submitAccount').click();
  await page.locator('#onboarding').waitFor({state:'visible'});const id=await page.evaluate(async()=>(await (await fetch('/api/me')).json()).user.id);manage({id:'local-test-owner'},{action:'tester',userId:id,approved:true});await page.locator('#profileCountry').selectOption('GB'); await page.locator('#profileNext').click(); await page.locator('#discover').waitFor({ state: 'visible' }); return page;
}
try {
  const host = await account('Host');
  const assets=await host.evaluate(async()=>{const {wallet}=await (await fetch('/api/gifts/wallet')).json();return Promise.all(wallet.gifts.map(async gift=>{const [thumb,animation]=await Promise.all([fetch(`/gifts/thumbs/${gift.codepoint}.svg`),fetch(`/gifts/animated/${gift.codepoint}.json`)]);return {id:gift.id,thumb:thumb.status,animation:animation.status};}));});
  assert.equal(assets.length,25);assert.ok(assets.every(x=>x.thumb===200&&x.animation===200),'All gift thumbnails and animations are self-hosted');
  const user = await host.evaluate(async () => (await (await fetch('/api/me')).json()).user); process.env.ADMIN_USER_IDS = `local-test-owner,${user.id}`;
  await host.reload();
  const viewerA = await account('ViewerA', true), viewerB = await account('ViewerB');
  await viewerA.locator('#roomSearch').fill('Host');await viewerA.locator('#hostDirectory').getByRole('button',{name:'Follow Host',exact:true}).click();await viewerA.locator('#hostDirectory').getByRole('button',{name:'Unfollow Host',exact:true}).click();await viewerA.locator('#clearRoomSearch').click();await viewerA.locator('#roomSearch').fill('Host');await viewerA.locator('#hostDirectory .person-card').filter({hasText:'Host'}).getByRole('button',{name:'View profile'}).click();await viewerA.locator('#followHost').click();await viewerA.waitForFunction(()=>document.getElementById('followHost').textContent==='Unfollow');await viewerA.locator('#closePublicProfile').click();await viewerA.locator('#navFollowing').click();await viewerA.locator('#followedHosts').getByText('Host',{exact:true}).waitFor();
  await host.locator('#navLive').click();await host.locator('#previewDevices').click();await host.waitForFunction(()=>document.getElementById('cameraPreview').videoWidth>0);assert.ok(await host.locator('#cameraDevice option').count()>1);await host.locator('#studioFilters [data-look=warm]').click();assert.equal(await host.locator('#studioFilters [data-look=warm]').getAttribute('aria-pressed'),'true');assert.ok((await host.locator('#cameraPreview').evaluate(e=>e.style.filter)).includes('sepia'));await host.locator('#studio .face-controls summary').click();await host.locator('#studioFaceEyes').fill('55');await host.waitForFunction(()=>document.getElementById('studioFaceStatus').textContent.includes('ready'),null,{timeout:30000});await host.waitForFunction(()=>document.getElementById('cameraPreview').style.filter==='none');await host.locator('#stopPreview').click();assert.equal(await host.locator('#cameraPreview').isVisible(),false);
 await host.locator('#start').click();assert.equal(await host.locator('#titleError').textContent(),'Enter a room title to go live.');assert.equal(await host.locator('#title').getAttribute('aria-invalid'),'true');await host.locator('#title').fill('Hi');await host.locator('#start').click();assert.equal(await host.locator('#titleError').textContent(),'Use at least 3 characters for the room title.');await host.locator('#title').fill('Browser live test');await host.locator('#start').click();assert.equal(await host.locator('#hostRulesError').textContent(),'Accept the room rules before going live.');await host.locator('#hostRules').check();await host.locator('#start').click();
  await host.waitForFunction(() => document.getElementById('status').textContent === 'You’re live', null, { timeout: 25000 });
  assert.equal(await host.locator('#local').getAttribute('data-filtered'), 'true', 'LiveKit publishes the filtered camera track');assert.equal(await host.locator('#local').evaluate(e => e.srcObject?.getVideoTracks()[0]?.readyState), 'live');
  assert.equal(await host.locator('#studioFilters button').count(),22);await host.setViewportSize({width:390,height:844});await host.locator('#openLiveFilters').click();assert.equal(await host.locator('#local').isVisible(),true);assert.equal(await host.locator('#room').evaluate(e=>e.classList.contains('filters-open')),true);assert.equal(await host.evaluate(()=>{const camera=document.querySelector('#videoStage').getBoundingClientRect(),panel=document.querySelector('#liveFilterDialog').getBoundingClientRect();return camera.height>innerHeight*.7&&panel.height<innerHeight*.3&&panel.top>=camera.bottom-1&&panel.bottom<=innerHeight+1;}),true,'Compact filter strip sits beneath a large camera preview on mobile');await host.locator('#liveFaceTab').click();assert.equal(await host.locator('#liveFacePanel').isVisible(),true);await host.locator('#liveFaceChoices [data-effect=Sparkle]').click();await host.locator('#liveFaceAmount').fill('60');assert.equal(await host.locator('#liveFaceAmountValue').textContent(),'60%');await host.locator('#liveLooksTab').click();await host.locator('#liveFilters [data-look=mono]').click();await host.locator('#liveFilterStrength').fill('85');assert.equal(await host.locator('#liveFilters [data-look=mono]').getAttribute('aria-pressed'),'true');await host.locator('#resetLiveFilters').click();await host.waitForFunction(() => document.getElementById('local').dataset.filtered === 'false');await host.locator('#liveFilters [data-look=warm]').click();await host.waitForFunction(() => document.getElementById('local').dataset.filtered === 'true');await host.locator('#closeLiveFilters').click();await host.setViewportSize({width:1280,height:900});
  await viewerA.locator('#navUpdates').click();await viewerA.getByText('Host is live: Browser live test',{exact:true}).waitFor();await viewerA.locator('#markUpdatesRead').click();await viewerA.waitForFunction(()=>document.getElementById('navUpdates').getAttribute('aria-label')==='Updates');
  for (const viewer of [viewerA, viewerB]) {
    await viewer.locator('#navHome').click();await viewer.locator('.room-item').click(); await viewer.locator('#viewerRules').check(); await viewer.locator('#confirmJoin').click();
    await viewer.waitForFunction(() => document.getElementById('remote').videoWidth > 0, null, { timeout: 25000 });
    assert.equal(await viewer.evaluate(() => document.querySelector('video').controls), false);assert.equal(await viewer.locator('#chatLog').evaluate(e => e.closest('#videoStage') !== null), true);
    assert.equal(await viewer.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
  }
  await host.waitForFunction(() => document.getElementById('viewerCount').textContent === '2');
  await viewerA.locator('#chatText').fill('Real browser chat'); await viewerA.locator('#chatForm button').click(); await viewerB.getByText('Real browser chat', { exact: true }).waitFor();await viewerA.locator('#chatSendStatus').getByText('Sent ✓').waitFor();
  await viewerA.locator('#openGifts').click();await viewerA.locator('.gift-choice img').first().waitFor();await viewerA.locator('#giftBalance').getByText('250').waitFor();assert.equal(await viewerA.locator('.gift-choice').count(),25);assert.equal(await viewerA.getByRole('button',{name:'Send Unicorn for 140 test credits'}).count(),1);await viewerA.locator('#giftRecipient').selectOption(user.id);await viewerA.getByRole('button',{name:'Send Heart for 5 test credits'}).click();assert.equal(await viewerA.locator('#roomConfirmDialog').isVisible(),true);await viewerA.locator('#acceptRoomConfirm').click();await viewerA.locator('#giftStatus').getByText('Gift sent ✓').waitFor();await host.locator('#chatLog').getByText('ViewerA sent ♥ Heart to Host').waitFor();await host.locator('#giftCelebration[data-gift=heart]').waitFor({state:'visible'});await host.locator('#giftCelebrationMotion svg').waitFor({state:'visible'});assert.equal(await host.locator('#giftCelebrationTitle').textContent(),'Heart');assert.equal(await viewerA.locator('#giftCelebration').isVisible(),true);assert.equal(await viewerA.locator('#giftBalance').textContent(),'245');await viewerA.locator('#closeGifts').click();
  const viewerAId=await viewerA.evaluate(async()=>(await (await fetch('/api/me')).json()).user.id),viewerBId=await viewerB.evaluate(async()=>(await (await fetch('/api/me')).json()).user.id);
  await viewerB.locator('#openGifts').click();await viewerB.locator('#giftRecipient').selectOption(viewerAId);await viewerB.getByRole('button',{name:'Send Star for 15 test credits'}).click();await viewerB.locator('#acceptRoomConfirm').click();await viewerA.locator('#chatLog').getByText('ViewerB sent ✦ Star to ViewerA').waitFor();await viewerB.locator('#closeGifts').click();
  await host.locator('#openGifts').click();await host.locator('#giftRecipient').selectOption(viewerBId);await host.getByRole('button',{name:'Send Flower for 30 test credits'}).click();await host.locator('#acceptRoomConfirm').click();await viewerB.locator('#chatLog').getByText('Host sent ✿ Flower to ViewerB').waitFor();await host.locator('#closeGifts').click();
  await viewerB.locator('#openReport').click(); await viewerB.locator('#reportDetails').fill('Synthetic report test'); await viewerB.locator('#reportForm button').last().click(); await viewerB.getByText('Report received. Thank you for helping keep Veya safe.').waitFor();
  await host.locator('#openViewers').click();await host.locator('.viewer').filter({ hasText: 'ViewerA' }).getByRole('button', { name: 'Remove' }).click();assert.equal(await host.locator('#roomConfirmDialog').isVisible(),true);assert.equal(await viewerA.locator('#room').isVisible(),true);await host.locator('#cancelRoomConfirm').click();assert.equal(await viewerA.locator('#room').isVisible(),true);await host.locator('.viewer').filter({ hasText: 'ViewerA' }).getByRole('button', { name: 'Remove' }).click();await host.locator('#acceptRoomConfirm').click(); await viewerA.getByText('The host removed you from this room.', { exact: true }).waitFor();
  await host.locator('#leave').click();assert.equal(await viewerB.locator('#room').isVisible(),true);await host.locator('#acceptRoomConfirm').click(); await viewerB.getByText('The host ended this room.', { exact: true }).waitFor();
  await viewerA.locator('#navProfile').click();await viewerA.locator('#profileTestGifts summary').click();await viewerA.locator('#profileGiftSummary').getByText('245 credits available · 5 sent · 15 received').waitFor();assert.equal(await viewerA.locator('#profileGiftHistory img').count(),2);
  await host.locator('#navProfile').click();await host.locator('#profileHostButton').click();await host.waitForFunction(() => document.querySelector('#hostStats')?.textContent.includes('1 lives'));assert.equal(await host.locator('#hostTestGiftTotal').textContent(),'5 points');await host.locator('#openAdmin').click();await host.locator('#adminReportsTab').click(); await host.getByText('Synthetic report test', { exact: true }).waitFor();await host.locator('#adminTabs [data-admin-view=gifts]').click();await host.waitForFunction(()=>document.querySelectorAll('#adminGifts .admin-gift-row').length===3);
  assert.deepEqual(errors, []); console.log('PASS: real media, 2 viewers, mobile layout, chat, report, host removal and cleanup');
} finally { await browser.close(); await new Promise(resolve => server.close(resolve)); rmSync(directory, { recursive: true, force: true }); }
