// Checks real account UI and honest unconfigured-media behavior. No media adapter.
import { chromium } from 'playwright';
import { strict as assert } from 'node:assert';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const directory = mkdtempSync(join(tmpdir(), 'veya-ui-')); process.env.DATA_FILE = join(directory, 'test.sqlite');
const { createApp } = await import('../server.mjs'); const { createMedia } = await import('../media.mjs');
process.env.ADMIN_USER_IDS='local-test-owner';const {manage}=await import('../access.mjs');
const { server } = createApp({ media: createMedia({}) }); await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const browser = await chromium.launch({ headless: true });
try {
  const errors = [];
  for (const viewport of [{ width: 390, height: 844 }, { width: 1280, height: 900 }]) {
    const context = await browser.newContext({ viewport }); const page = await context.newPage(); page.on('pageerror', error => errors.push(error.message));
    await page.goto(`http://127.0.0.1:${server.address().port}`);
    await page.locator('#toggleAccount').click(); await page.locator('#displayName').fill('UI tester'); await page.locator('#adult').check(); await page.locator('#email').fill(`ui-${viewport.width}@example.test`); await page.locator('#password').fill('a long test password'); await page.locator('#submitAccount').click(); await page.locator('#onboarding').waitFor({ state: 'visible' }); const userId=await page.evaluate(async()=>(await (await fetch('/api/me')).json()).user.id);manage({id:'local-test-owner'},{action:'tester',userId:userId,approved:true}); await page.locator('#profileCountry').selectOption('GB'); await page.locator('#profileBio').fill('Music and good conversations'); const photo = await page.evaluate(() => {const c=document.createElement('canvas');c.width=20;c.height=20;c.getContext('2d').fillRect(0,0,20,20);return c.toDataURL('image/png').split(',')[1];}); await page.locator('#avatarFile').setInputFiles({name:'photo.png',mimeType:'image/png',buffer:Buffer.from(photo,'base64')}); await page.locator('#avatarPreview img').waitFor(); await page.locator('#profileNext').click(); await page.locator('#discover').waitFor({ state: 'visible' });
    assert.equal(await page.locator('#interestChoices').count(),0);await page.locator('#navFollowing').click();await page.getByText('You haven’t followed any hosts yet.',{exact:false}).waitFor();await page.locator('#navProfile').click();await page.locator('#profileHostButton').click();await page.getByText('0 live hours · 0 streaming days · 0 sessions',{exact:true}).waitFor();await page.locator('#navUpdates').click();await page.getByText('Your host updates and access decisions will appear here.',{exact:true}).waitFor();
    await page.locator('#navLive').click(); assert.equal(await page.locator('#profile').isVisible(),true); assert.equal(await page.locator('#applyHost').isVisible(),true); assert.match(await page.locator('#setupState').textContent(), /not connected/);
    assert.equal(await page.locator('.room-item').count(), 0); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.locator('#navProfile').click(); assert.equal(await page.locator('#profileAvatar img').count(),1); assert.equal(await page.locator('#profileAbout').textContent(), 'Music and good conversations'); await page.locator('#profileSettingsButton').click();assert.equal(await page.locator('#profileAccountSettings').getAttribute('open'),'');await page.locator('#profileAccountSettings summary').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#logout').click(); await page.locator('#account').waitFor({ state: 'visible' });
    await page.locator('#toggleAccount').click(); await page.locator('#email').fill(`ui-${viewport.width}@example.test`); await page.locator('#password').fill('a long test password'); await page.locator('#submitAccount').click(); await page.locator('#discover').waitFor({ state: 'visible' });
    assert.equal(await page.locator('#onboarding').isVisible(), false); await page.locator('#navProfile').click(); await page.locator('#editProfile').click(); await page.locator('#profileName').fill('Updated member');await page.locator('#profileAge').fill('23');await page.locator('#profileHobbies').getByLabel('Music',{exact:true}).check();await page.locator('#profileHobbies').getByLabel('Football',{exact:true}).check(); await page.locator('#profileNext').click(); await page.locator('#profile').waitFor({state:'visible'}); assert.equal(await page.locator('#profileDisplayName').textContent(),'Updated member');assert.equal(await page.locator('#profileAgeLabel').textContent(),'23 years old');assert.equal(await page.locator('#profileHobbyTags span').count(),2);await page.locator('#viewOwnPublicProfile').click();await page.locator('#publicProfileDialog').waitFor({state:'visible'});assert.equal(await page.locator('#publicCountry').textContent(),'United Kingdom');assert.equal(await page.locator('#publicAge').textContent(),'23 years old');assert.equal(await page.locator('#publicHobbyTags span').count(),2);assert.equal(await page.locator('#publicFollowers').textContent(),'0');assert.equal(await page.evaluate(()=>document.getElementById('publicProfileDialog').scrollWidth>document.getElementById('publicProfileDialog').clientWidth),false);await page.locator('#closePublicProfile').click(); assert.equal(await page.locator('#openAdmin').isVisible(), false); if(viewport.width===1280){process.env.ADMIN_USER_IDS=`local-test-owner,${userId}`;await page.reload();await page.locator('#openAdmin').click();await page.getByRole('heading',{name:'Admin console'}).waitFor();await page.locator('[data-admin-view=accounts]').click();assert.ok(await page.locator('.admin-member').count()>0);assert.equal(await page.locator('#trialSettings').isVisible(),false);await page.locator('[data-admin-view=settings]').click();await page.getByRole('heading',{name:'Trial and access settings'}).waitFor();assert.equal(await page.locator('#adminReportsTab').isVisible(),true);await page.locator('#adminReportsTab').click();await page.getByText('No reports yet.',{exact:true}).waitFor();await page.locator('#closeAdmin').click();} await context.close();
  }
  assert.deepEqual(errors, []); console.log('PASS: desktop/mobile signup, onboarding, photo upload, persisted profile editing, navigation, no overflow and sign-in');
} finally { await browser.close(); await new Promise(resolve => server.close(resolve)); rmSync(directory, { recursive: true, force: true }); }
